/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteImport } from './routes/web'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebProjectsRouteImport } from './routes/web/projects'
import { Route as WebLoginRouteImport } from './routes/web/login'
import { Route as WebAuthenticatedRouteImport } from './routes/web/_authenticated'
import { Route as WebProjectsIndexRouteImport } from './routes/web/projects/index'
import { Route as WebAuthenticatedIndexRouteImport } from './routes/web/_authenticated/index'
import { Route as WebProjectsOverviewRouteImport } from './routes/web/projects.overview'
import { Route as WebAuthenticatedAccountRouteImport } from './routes/web/_authenticated/account'

const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebProjectsRoute = WebProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WebRoute,
} as any)
const WebLoginRoute = WebLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WebRoute,
} as any)
const WebAuthenticatedRoute = WebAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => WebRoute,
} as any)
const WebProjectsIndexRoute = WebProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebProjectsRoute,
} as any)
const WebAuthenticatedIndexRoute = WebAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebAuthenticatedRoute,
} as any)
const WebProjectsOverviewRoute = WebProjectsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WebProjectsRoute,
} as any)
const WebAuthenticatedAccountRoute = WebAuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WebAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/web': typeof WebAuthenticatedRouteWithChildren
  '/web/login': typeof WebLoginRoute
  '/web/projects': typeof WebProjectsRouteWithChildren
  '/web/account': typeof WebAuthenticatedAccountRoute
  '/web/projects/overview': typeof WebProjectsOverviewRoute
  '/web/': typeof WebAuthenticatedIndexRoute
  '/web/projects/': typeof WebProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/web': typeof WebAuthenticatedIndexRoute
  '/web/login': typeof WebLoginRoute
  '/web/account': typeof WebAuthenticatedAccountRoute
  '/web/projects/overview': typeof WebProjectsOverviewRoute
  '/web/projects': typeof WebProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/web': typeof WebRouteWithChildren
  '/web/_authenticated': typeof WebAuthenticatedRouteWithChildren
  '/web/login': typeof WebLoginRoute
  '/web/projects': typeof WebProjectsRouteWithChildren
  '/web/_authenticated/account': typeof WebAuthenticatedAccountRoute
  '/web/projects/overview': typeof WebProjectsOverviewRoute
  '/web/_authenticated/': typeof WebAuthenticatedIndexRoute
  '/web/projects/': typeof WebProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/web'
    | '/web/login'
    | '/web/projects'
    | '/web/account'
    | '/web/projects/overview'
    | '/web/'
    | '/web/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/web'
    | '/web/login'
    | '/web/account'
    | '/web/projects/overview'
    | '/web/projects'
  id:
    | '__root__'
    | '/'
    | '/web'
    | '/web/_authenticated'
    | '/web/login'
    | '/web/projects'
    | '/web/_authenticated/account'
    | '/web/projects/overview'
    | '/web/_authenticated/'
    | '/web/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WebRoute: typeof WebRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web/projects': {
      id: '/web/projects'
      path: '/projects'
      fullPath: '/web/projects'
      preLoaderRoute: typeof WebProjectsRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/login': {
      id: '/web/login'
      path: '/login'
      fullPath: '/web/login'
      preLoaderRoute: typeof WebLoginRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/_authenticated': {
      id: '/web/_authenticated'
      path: ''
      fullPath: '/web'
      preLoaderRoute: typeof WebAuthenticatedRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/projects/': {
      id: '/web/projects/'
      path: '/'
      fullPath: '/web/projects/'
      preLoaderRoute: typeof WebProjectsIndexRouteImport
      parentRoute: typeof WebProjectsRoute
    }
    '/web/_authenticated/': {
      id: '/web/_authenticated/'
      path: '/'
      fullPath: '/web/'
      preLoaderRoute: typeof WebAuthenticatedIndexRouteImport
      parentRoute: typeof WebAuthenticatedRoute
    }
    '/web/projects/overview': {
      id: '/web/projects/overview'
      path: '/overview'
      fullPath: '/web/projects/overview'
      preLoaderRoute: typeof WebProjectsOverviewRouteImport
      parentRoute: typeof WebProjectsRoute
    }
    '/web/_authenticated/account': {
      id: '/web/_authenticated/account'
      path: '/account'
      fullPath: '/web/account'
      preLoaderRoute: typeof WebAuthenticatedAccountRouteImport
      parentRoute: typeof WebAuthenticatedRoute
    }
  }
}

interface WebAuthenticatedRouteChildren {
  WebAuthenticatedAccountRoute: typeof WebAuthenticatedAccountRoute
  WebAuthenticatedIndexRoute: typeof WebAuthenticatedIndexRoute
}

const WebAuthenticatedRouteChildren: WebAuthenticatedRouteChildren = {
  WebAuthenticatedAccountRoute: WebAuthenticatedAccountRoute,
  WebAuthenticatedIndexRoute: WebAuthenticatedIndexRoute,
}

const WebAuthenticatedRouteWithChildren =
  WebAuthenticatedRoute._addFileChildren(WebAuthenticatedRouteChildren)

interface WebProjectsRouteChildren {
  WebProjectsOverviewRoute: typeof WebProjectsOverviewRoute
  WebProjectsIndexRoute: typeof WebProjectsIndexRoute
}

const WebProjectsRouteChildren: WebProjectsRouteChildren = {
  WebProjectsOverviewRoute: WebProjectsOverviewRoute,
  WebProjectsIndexRoute: WebProjectsIndexRoute,
}

const WebProjectsRouteWithChildren = WebProjectsRoute._addFileChildren(
  WebProjectsRouteChildren,
)

interface WebRouteChildren {
  WebAuthenticatedRoute: typeof WebAuthenticatedRouteWithChildren
  WebLoginRoute: typeof WebLoginRoute
  WebProjectsRoute: typeof WebProjectsRouteWithChildren
}

const WebRouteChildren: WebRouteChildren = {
  WebAuthenticatedRoute: WebAuthenticatedRouteWithChildren,
  WebLoginRoute: WebLoginRoute,
  WebProjectsRoute: WebProjectsRouteWithChildren,
}

const WebRouteWithChildren = WebRoute._addFileChildren(WebRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WebRoute: WebRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
