import { Hono } from "hono";
import { cors } from "hono/cors";
import { requestLogger } from "./middleware/request-logger.js";
import { errorHandler } from "./middleware/error-handler.js";
import { health } from "./routes/health.js";
import { projects } from "./routes/projects.js";
import { sources } from "./routes/sources.js";
import { sessions } from "./routes/sessions.js";
import { artifacts } from "./routes/artifacts.js";
import { sprints } from "./routes/sprints.js";
import { harness } from "./routes/harness.js";
import { reviews } from "./routes/reviews.js";
import { metrics } from "./routes/metrics.js";
import { contextProfiles } from "./routes/context-profiles.js";
import { context } from "./routes/context.js";
import { reviewAgents } from "./routes/review-agents.js";
import { agentReview } from "./routes/agent-review.js";
import { mcpServers } from "./routes/mcp-servers.js";
import { qualityGates } from "./routes/quality-gates.js";
import { snapshots } from "./routes/snapshots.js";
import { burnout } from "./routes/burnout.js";
import { taskComplexity } from "./routes/task-complexity.js";
import { artifactOrigins } from "./routes/artifact-origins.js";
import { prompts } from "./routes/prompts.js";
import { docs } from "./routes/docs.js";
import { defects } from "./routes/defects.js";
import { autonomy } from "./routes/autonomy.js";
import { productivity } from "./routes/productivity.js";
import { evaluations } from "./routes/evaluations.js";
import { compliance } from "./routes/compliance.js";
import { acrs } from "./routes/acrs.js";
import { tokenUsage } from "./routes/token-usage.js";
import { agentActions } from "./routes/agent-actions.js";
import { handoffRequests } from "./routes/handoff-requests.js";
import { board } from "./routes/board.js";
import { qualityGateConfigs } from "./routes/quality-gate-configs.js";
import { modelRouting } from "./routes/model-routing.js";
import { testCoverageResults } from "./routes/test-coverage-results.js";
import { contributionQualityResults } from "./routes/contribution-quality-results.js";
import { learningMode } from "./routes/learning-mode.js";
import { containmentPolicies } from "./routes/containment-policies.js";
import { specs } from "./routes/specs.js";
import { security } from "./routes/security.js";
import { featureCycles } from "./routes/feature-cycles.js";
import { mentoringProfiles } from "./routes/mentoring-profiles.js";
import { driftEvents } from "./routes/drift-events.js";
import { throughputMetrics } from "./routes/throughput-metrics.js";
import { roi } from "./routes/roi.js";
import { learningCheckpoints } from "./routes/learning-checkpoints.js";
import { rescue } from "./routes/rescue.js";
import { platform } from "./routes/platform.js";
import { search } from "./routes/search.js";
import { cognitiveDebt } from "./routes/cognitive-debt.js";
import { pipeline } from "./routes/pipeline.js";
import { reviewPipelines } from "./routes/review-pipelines.js";

const app = new Hono();

// Global middleware
app.use("*", cors());
app.use("*", requestLogger());

// Global error handler
app.onError(errorHandler);

// Routes
app.route("/api/v1", health);
app.route("/api/v1", projects);
app.route("/api/v1", sources);
app.route("/api/v1", sessions);
app.route("/api/v1", artifacts);
app.route("/api/v1", sprints);
app.route("/api/v1", harness);
app.route("/api/v1", reviews);
app.route("/api/v1", metrics);
app.route("/api/v1", contextProfiles);
app.route("/api/v1", context);
app.route("/api/v1", reviewAgents);
app.route("/api/v1", agentReview);
app.route("/api/v1", mcpServers);
app.route("/api/v1", qualityGates);
app.route("/api/v1", snapshots);
app.route("/api/v1", burnout);
app.route("/api/v1", taskComplexity);
app.route("/api/v1", artifactOrigins);
app.route("/api/v1", prompts);
app.route("/api/v1", docs);
app.route("/api/v1", defects);
app.route("/api/v1", autonomy);
app.route("/api/v1", productivity);
app.route("/api/v1", evaluations);
app.route("/api/v1", compliance);
app.route("/api/v1", acrs);
app.route("/api/v1", tokenUsage);
app.route("/api/v1", agentActions);
app.route("/api/v1", handoffRequests);
app.route("/api/v1", board);
app.route("/api/v1", qualityGateConfigs);
app.route("/api/v1", modelRouting);
app.route("/api/v1", testCoverageResults);
app.route("/api/v1", contributionQualityResults);
app.route("/api/v1", learningMode);
app.route("/api/v1", containmentPolicies);
app.route("/api/v1", specs);
app.route("/api/v1", security);
app.route("/api/v1", featureCycles);
app.route("/api/v1", mentoringProfiles);
app.route("/api/v1", driftEvents);
app.route("/api/v1", throughputMetrics);
app.route("/api/v1", roi);
app.route("/api/v1", learningCheckpoints);
app.route("/api/v1", rescue);
app.route("/api/v1", platform);
app.route("/api/v1", search);
app.route("/api/v1", cognitiveDebt);
app.route("/api/v1", pipeline);
app.route("/api/v1", reviewPipelines);

export { app };
