/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellProfileRouteImport } from './routes/_shell/profile'
import { Route as ShellNotificationsRouteImport } from './routes/_shell/notifications'
import { Route as ShellSettingsIndexRouteImport } from './routes/_shell/settings/index'
import { Route as ShellSettingsThemeRouteImport } from './routes/_shell/settings/theme'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsIndexRoute = ShellSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsThemeRoute = ShellSettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => ShellSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof ShellNotificationsRoute
  '/profile': typeof ShellProfileRoute
  '/settings': typeof ShellSettingsRouteWithChildren
  '/settings/theme': typeof ShellSettingsThemeRoute
  '/settings/': typeof ShellSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/notifications': typeof ShellNotificationsRoute
  '/profile': typeof ShellProfileRoute
  '/': typeof ShellIndexRoute
  '/settings/theme': typeof ShellSettingsThemeRoute
  '/settings': typeof ShellSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/settings': typeof ShellSettingsRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/settings/theme': typeof ShellSettingsThemeRoute
  '/_shell/settings/': typeof ShellSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/settings/theme'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notifications'
    | '/profile'
    | '/'
    | '/settings/theme'
    | '/settings'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/notifications'
    | '/_shell/profile'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/settings/theme'
    | '/_shell/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/': {
      id: '/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ShellSettingsIndexRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/theme': {
      id: '/_shell/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof ShellSettingsThemeRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
  }
}

interface ShellSettingsRouteChildren {
  ShellSettingsThemeRoute: typeof ShellSettingsThemeRoute
  ShellSettingsIndexRoute: typeof ShellSettingsIndexRoute
}

const ShellSettingsRouteChildren: ShellSettingsRouteChildren = {
  ShellSettingsThemeRoute: ShellSettingsThemeRoute,
  ShellSettingsIndexRoute: ShellSettingsIndexRoute,
}

const ShellSettingsRouteWithChildren = ShellSettingsRoute._addFileChildren(
  ShellSettingsRouteChildren,
)

interface ShellRouteChildren {
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellSettingsRoute: typeof ShellSettingsRouteWithChildren
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellSettingsRoute: ShellSettingsRouteWithChildren,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
